language: python
os: linux
dist: xenial

matrix:
    include:
        - python: 3.6

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y ffmpeg; fi

install:
    - pip install -r requirements.txt
    - pip install pylint

script:
    - pylint subsets tests setup.py
    - python setup.py test
